#
# Module manifest for the module Powershell-Productivity
#
# Generated by : K. Siva Senthil
#
# Generated on : 26-May-2018
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule="PowerShell-Productivity.psm1"

    # Version number of this module
    ModuleVersion ="1.0.0"

    # ID used to uniquel idenify this module
    GUID="7e4aec0d-4bee-4e61-9c75-7ea62209eebd"

    # Author of this module
    Author="K. Siva Senthil"

    # Company or vendor of this module
    CompanyName="VOS"

    # Copyright statement for this module
    Copyright="(c) 2018 MIT License @ https://github.com/ksivasenthil/PowerShell-Productivity/blob/master/LICENSE"

    # Description of the functionality provided by the module
    Description="This module hosts the scripts which will help you be more productive at work using PowerShell"

    # Minimum version of the Windows PowerShell engine required for this module
    PowerShellVersion = "4.0"

    # Name of the Windows PowerShell host required by the this module
    #PowerShellHostName=""

    # Minimum Version of the Windows PowerShell host required by this module
    #PowerShellHostVersion=""

    # Minimum version of the .NET framework required by this module
    #DotNetFrameworkVersion=""

    # Minimum version of the CLR required by this module
    #CLRVersion=""

    # Processor architecture (x86, AMD, x64) required for this module
    #ProcessorArchitecture=""

    # Modules that must be imported into the global environment before importing this module
    #RequiredModules=@()

    # Script files (.ps1) that are run in the callers environment before importing this module
    #ScriptsToProcess=@()

    # Type files (.ps1xml) to be loaded when importing this module
    #TypesToProcess=@()

    # Format files (.ps1xml) to be loaded when importing this module
    #FormatsToProcess=@()

    # Modules to import as nested module to the module specified in RootMoudle/ModuleToProcess
    #NestedModule=@()

    # Functions to export from this module
    FunctionsToExport="*"

    # Cmdlets to export from this module
    CmdletsToExport="*"

    # Variables to export from this module
    VariablesToExport="*"

    # Aliases to export from this module
    AliasesToExport="*"

    # List of all modules packaged within this module
    #ModuleList=@()

    # List of all files packaged within this module
    #FileList=@()

    # Private data to pass to the module specified in the RootModule/ModuleToProcess
    #PrivateData=""

    # HelpInfo URI for this module
    #HelpInfoURI=""

    # Default prefix for the commands exported from this module. Override default prefix using Import-Module -Prefix.
    #DefaultCommandPrefix=""

}